declare module 'slash2';
declare module '*.css';
declare module '*.less';
declare module '*.scss';
declare module '*.sass';
declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.bmp';
declare module '*.tiff';
declare module 'crypto-js'
declare module 'nprogress';
declare module 'zxcvbn';
declare module 'lodash-es';
declare module '@/utils/oneapi/constants/channel';
declare module '@/utils/oneapi/common';
declare module '@/components/oneapi/ResponseTimeLabel';
// declare module 'sonner';
// declare module 'react18-json-view';